apiVersion: apps/v1
kind: Deployment
metadata:
  name: freedom-fighters-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: freedom-fighters
  template:
    metadata:
      labels:
        app: freedom-fighters
    spec:
      containers:
      - name: freedom-fighters
        image: shivagopaluni/freedom-fighters:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: freedom-fighters-service
spec:
  type: NodePort
  selector:
    app: freedom-fighters
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007

